# Generated by Django 5.0.2 on 2024-02-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='coatings/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LensFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='features/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LensIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LensMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='materials/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SV', 'SV'), ('KT', 'KT'), ('Progressive', 'Progressive')], max_length=20)),
                ('brand_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='stock_lenses/')),
                ('description', models.TextField()),
                ('features', models.ManyToManyField(to='home.lensfeatures')),
                ('lens_coating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lenscoating')),
                ('lens_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lensindex')),
                ('lens_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lensmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PowerRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIA', models.CharField(max_length=20)),
                ('power_range', models.CharField(max_length=50)),
                ('price_srp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lens_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stocklens')),
            ],
        ),
    ]
