# Generated by Django 5.0.2 on 2024-02-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lenscoating_lensfeatures_lensindex_lensmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/assets/lens_types/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lenscoating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lenscoating',
            name='photo',
            field=models.ImageField(upload_to='static/assets/coatings/'),
        ),
        migrations.AlterField(
            model_name='lensfeatures',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lensfeatures',
            name='image',
            field=models.ImageField(upload_to='static/assets/features/'),
        ),
        migrations.AlterField(
            model_name='lensindex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lensmaterial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lensmaterial',
            name='image',
            field=models.ImageField(upload_to='static/assets/materials/'),
        ),
        migrations.AlterField(
            model_name='powerrange',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocklens',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocklens',
            name='image',
            field=models.ImageField(upload_to='static/assets/stock_lenses/'),
        ),
        migrations.AlterField(
            model_name='stocklens',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lenstypes'),
        ),
    ]
