# Generated by Django 5.0.2 on 2024-02-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lenstypes_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LensFeatures',
            new_name='LensFeature',
        ),
        migrations.RenameModel(
            old_name='LensTypes',
            new_name='LensType',
        ),
    ]
